PALAVRAS_CHAVE_ENGENHARIA_MATEMATICA = [
    'estrutura', 'estruturas', 'concreto', 'concretos', 'ponte', 'pontes', 'engenharia civil', 'edificação', 'edificações', 'cálculo', 'cálculos', 'resistência', 'resistências', 
    'física', 'físicas', 'material de construção', 'materiais de construção', 'hidráulica', 'hidráulicas', 'solo', 'solos', 'fundação', 'fundações', 'matemática', 'álgebra',
    'geometria', 'geometrias', 'trigonometria', 'trigonometrias', 'cálculo diferencial', 'cálculo integral', 'integral', 'integrais', 'engenharia estrutural', 'viga', 'vigas',
    'diferencial', 'diferenciais', 'mecânica', 'mecânicas', 'tensão', 'tensões', 'carga', 'cargas', 'torre', 'torres', 'dimensionamento', 'dimensionamentos', 'fator de segurança', 'fatores de segurança',
    'engenharia geotécnica', 'topografia', 'topografias', 'pavimentação', 'pavimentações', 'drenagem', 'drenagens', 'infraestrutura', 'infraestruturas', 'túnel', 'túneis', 
    'viaduto', 'viadutos', 'sistema estrutural', 'sistemas estruturais', 'engenharia de transportes', 'geologia aplicada', 'carga estrutural', 'cargas estruturais', 
    'norma técnica', 'normas técnicas', 'projeto estrutural', 'projetos estruturais', 'muro de arrimo', 'muros de arrimo', 'patologia das construções', 'patologias das construções', 
    'segurança estrutural', 'seguranças estruturais', 'cimento', 'argamassa', 'concreto armado', 'concretos armados', 'concreto protendido', 'concretos protendidos', 
    'estrutura metálica', 'estruturas metálicas', 'alvenaria estrutural', 'alvenarias estruturais', 'ponte suspensa', 'pontes suspensas', 'engenharia hidráulica', 'sistema de abastecimento', 'sistemas de abastecimento',
    'saneamento', 'saneamentos', 'tratamento de água', 'tratamentos de água', 'esgoto', 'esgotos', 'irrigação', 'irrigações', 'barragem', 'barragens',
    'engenharia ambiental', 'sustentabilidade', 'sustentabilidades', 'construção civil', 'construções civis', 'cantilever', 'método dos elementos finitos', 'engenharia de tráfego',
    'conforto térmico', 'confortos térmicos', 'acústica', 'acústicas', 'engenharia de custos', 'gestão de projeto', 'gestões de projetos', 'cronograma de obra', 'cronogramas de obras', 'análise estrutural', 'análises estruturais',
    'cálculo de viga', 'cálculos de vigas', 'cálculo de pilares', 'engenharia de materiais', 'desempenho estrutural', 'norma de segurança', 'normas de segurança', 'tensão admissível', 'tensões admissíveis',
    'dimensionamento de fundação', 'dimensionamentos de fundações', 'movimentação de terra', 'movimentações de terra', 'maquinário de construção', 'maquinários de construção', 'projeto de edificação', 'projetos de edificações',
    'matemática', 'álgebra', 'geometria', 'geometrias', 'trigonometria', 'trigonometrias', 'cálculo diferencial', 'cálculo integral', 'limite', 'limites', 'função', 'funções',
    'equação diferencial', 'equações diferenciais', 'série de taylor', 'séries de taylor', 'número complexo', 'números complexos', 'análise matemática', 'matriz', 'matrizes', 'determinante', 'determinantes',
    'sistema linear', 'sistemas lineares', 'vetor', 'vetores', 'geometria analítica', 'probabilidade', 'probabilidades', 'estatística', 'estatísticas', 'combinatória', 'combinatórias', 'progressão aritmética', 'progressões aritméticas',
    'progressão geométrica', 'progressões geométricas', 'teoria dos números', 'matemática financeira', 'logaritmo', 'logaritmos', 'exponencial', 'exponenciais', 'raiz', 'raízes', 'fração', 'frações',
    'tangente', 'tangentes', 'derivada', 'derivadas', 'integração por partes', 'equação algébrica', 'equações algébricas', 'polinômio', 'polinômios', 'transformada de laplace',
    'geometria espacial', 'teorema de pitágoras', 'teoremas de pitágoras', 'teorema de trigonometria', 'teoremas de trigonometria', 'área', 'áreas', 'volume', 'volumes', 'comprimento de arco', 'comprimentos de arco',
    'circunferência', 'circunferências', 'raio', 'raios', 'diâmetro', 'diâmetros', 'seno', 'senos', 'cosseno', 'cossenos', 'cotangente', 'cotangentes', 'secante', 'secantes', 'co-secante', 'co-secantes',
    'fatoração', 'fatoraçãos', 'número primo', 'números primos', 'teorema fundamental da álgebra', 'regressão linear', 'regressões lineares', 'análise de dados', 'medida de tendência central', 'medidas de tendência central',
    'média', 'médias', 'mediana', 'moda', 'variância', 'variâncias', 'desvio padrão', 'desvios padrões', 'distribuição normal', 'distribuições normais', 'distribuição binomial', 'distribuições binomiais', 'hipótese estatística', 'hipóteses estatísticas',
    'equação de segundo grau', 'equações de segundo grau', 'equação paramétrica', 'equações paramétricas', 'ponto crítico', 'pontos críticos', 'intervalo de confiança', 'intervalos de confiança', 'correlação', 'correlações',
    'análise combinatória', 'análises combinatórias', 'binômio de newton', 'limite lateral', 'função logarítmica', 'funções logarítmicas', 'função exponencial', 'funções exponenciais', 'cálculo numérico', 'probabilidade condicional',
    'geotecnia', 'construção sustentável', 'edifício inteligente', 'edifícios inteligentes', 'engenharia urbana', 'sistema de transporte público', 'sistemas de transporte público', 'mobilidade urbana', 'eficiência energética', 'eficiências energéticas',
    'isolamento térmico', 'isolamentos térmicos', 'avaliação de impacto ambiental', 'avaliações de impacto ambiental', 'licenciamento ambiental', 'perícia de obra', 'perícias de obras', 'terraplenagem', 'tecnologia do concreto',
    'estabilidade de taludes', 'controle de erosão', 'qualidade da água', 'planejamento urbano', 'infraestrutura verde', 'gestão de resíduos', 'reaproveitamento de material', 'reaproveitamento de materiais', 'reciclagem de concreto', 'avaliação estrutural',
    'ponte de concreto', 'pontes de concreto', 'ponte de aço', 'pontes de aço', 'estrutura de madeira', 'estruturas de madeira', 'sistema pré-moldado', 'sistemas pré-moldados', 'túnel submerso', 'túneis submersos',
    'engenharia costeira', 'proteção contra enchente', 'proteções contra enchentes', 'levantamento topográfico', 'análise sísmica', 'resposta estrutural', 'respostas estruturais', 'engenharia de fundações', 'estrutura hiperestática', 'estruturas hiperestáticas',
    'análise de estabilidade', 'carga de vento', 'cargas de vento', 'engenharia de minas', 'exploração de recurso natural', 'exploração de recursos naturais', 'equipamento de construção', 'equipamentos de construção', 'automação na construção',
    'planejamento de canteiro', 'planejamentos de canteiros', 'sistema hidráulico', 'sistemas hidráulicos', 'sistema elétrico predial', 'sistemas elétricos prediais', 'orçamento de obra', 'orçamentos de obras', 'logística de material', 'logísticas de materiais',
    'prevenção de desastres', 'infraestrutura crítica', 'infraestruturas críticas', 'ponte estaiada', 'pontes estaiadas', 'construção modular', 'construções modulares', 'pré-fabricação', 'isolamento acústico', 'isolamentos acústicos',
    'resíduo da construção', 'resíduos da construção', 'demolição', 'demolições', 'recuperação estrutural', 'recuperações estruturais', 'ensaio não destrutivo', 'ensaios não destrutivos', 'trinca', 'trincas', 'fissura', 'fissuras',
    'monitoramento estrutural', 'duto subterrâneo', 'dutos subterrâneos', 'bombeamento de concreto', 'concreto auto-adensável', 'concretos auto-adensáveis'
]
